### ISSUE TITLE
Exception in Database.php when database logging driver enabled

### ISSUE THREAD

**Issue by TheDarkLordRises** [Cherry-Pie/LogEnvelope#17]
I'm seeing an 'Array to string conversion' error in src/Drivers/Database.php when I have the database logging driver enabled.  
It's down to this line:       
``` $data['exegutor'] = implode('<br>', $data['exegutor']);```

$data['exegutor'] looks to be an array of arrays, rather than an array of strings, so the implode fails.

Full stack trace here:
```
[2019-09-06 14:02:21] local.ERROR: ErrorException: Array to string conversion in /home/vagrant/code/lucifer/vendor/yaro/log-envelope/src/Drivers/Database.php:23
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Array to string...', '/home/vagrant/c...', 23, Array)
#1 /home/vagrant/code/lucifer/vendor/yaro/log-envelope/src/Drivers/Database.php(23): implode('<br>', Array)
#2 /home/vagrant/code/lucifer/vendor/yaro/log-envelope/src/LogEnvelope.php(37): Yaro\LogEnvelope\Drivers\Database->send()
#3 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(239): Yaro\LogEnvelope\LogEnvelope->send(Object(Illuminate\Auth\AuthenticationException))
#4 /home/vagrant/code/lucifer/app/Exceptions/Handler.php(38): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#5 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(81): App\Exceptions\Handler->report(Object(Illuminate\Auth\AuthenticationException))
#6 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(55): Illuminate\Routing\Pipeline->handleException(Object(Illuminate\Http\Request), Object(Illuminate\Auth\AuthenticationException))
#7 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(58): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#8 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Routing\Middleware\ThrottleRequests->handle(Object(Illuminate\Http\Request), Object(Closure), 60, '1')
#9 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#11 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#12 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#13 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#14 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#15 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#17 /home/vagrant/code/lucifer/vendor/spatie/laravel-http-logger/src/Middlewares/HttpLogger.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Spatie\HttpLogger\Middlewares\HttpLogger->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /home/vagrant/code/lucifer/vendor/barryvdh/laravel-cors/src/HandleCors.php(36): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Barryvdh\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /home/vagrant/code/lucifer/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#40 /home/vagrant/code/lucifer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#41 /home/vagrant/code/lucifer/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#42 {main} 
```

**Comment by Cherry-Pie** [comment]
Thanks. It's under 1.6.0 now
